export default function useEnv() {
  const {
    VITE_DEV_SERVER_URL,
    VITE_DEV_SERVER_PORT,
    VITE_DEV_SERVER_CLIENT_PORT,
    VITE_TITLE,
    VITE_API_BASE_URL,
    VITE_LOCALE,
    VITE_API_ACCESS_KEY,
    VITE_PREFIX,
    VITE_MAINTENANCE_MODE,
  } = import.meta.env;

  return {
    APP_PREFIX: VITE_PREFIX || 'speediz',
    APP_TITLE: VITE_TITLE || 'speediz',
    APP_LOCALE: VITE_LOCALE || 'kh',
    APP_API_URL: VITE_API_BASE_URL,
    APP_API_ACESS_KEY: VITE_API_ACCESS_KEY,
    DEV_SERVER_URL: VITE_DEV_SERVER_URL,
    DEV_SERVER_PORT: VITE_DEV_SERVER_PORT,
    DEV_SERVER_CLIENT_PORT: VITE_DEV_SERVER_CLIENT_PORT,
    MAINTENANCE_MODE: VITE_MAINTENANCE_MODE,
  };
}
