#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🧪 Source code analaysis..."

# eslint --fix --no-error-on-unmatched-pattern $(git diff --name-only HEAD | grep '^resources/js/.*\.\(vue\|js\)$' | xargs)
